In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('Data/nyt_president.csv')

In [3]:
df.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,...,url_topline,url_crosstab,source,internal,partisan,politician,politician_id,yes,no,alternate_answers
0,9f87c793-4cef-4008-84d7-a403d9e40d8a,5a7ec4cc-59c7-44e0-b7c0-e78c05f19438,GBAO,"2d85208a-737f-45c9-98f2-d3d7e1eeac67,4d929913-...",Care in Action | Community Change Action | FWD.us,GBAO,109.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,43.0,57.0,NaN
1,426a32fd-aeb3-4220-a8d9-28d0317c7165,c429da10-5aa0-445e-9800-039c0a295b43,SurveyMonkey,4678387e-860f-4e2a-901e-183baf18cf83,NBC News Decision Desk,SurveyMonkey,324.0,SurveyMonkey,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,39.0,61.0,NaN
2,0936b486-6693-4ba2-908b-7646a89b62c7,59ef5d62-c6ba-41a3-b2cd-24b8543e62b9,YouGov,146144a2-08d6-4c6b-b912-f067ed647252,Economist,YouGov,391.0,YouGov,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,37.0,56.0,6.0
3,0936b486-6693-4ba2-908b-7646a89b62c7,59ef5d62-c6ba-41a3-b2cd-24b8543e62b9,YouGov,146144a2-08d6-4c6b-b912-f067ed647252,Economist,YouGov,391.0,YouGov,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,40.0,57.0,3.0
4,77b02317-04b6-4540-800a-8a665f6f51f8,4bc528cc-f55c-4f8b-8c90-adfe09f46c76,Morning Consult,NaN,NaN,Morning Consult,218.0,Morning Consult,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,40.0,54.2,5.8

In [4]:
list(df)

['poll_id',
 'pollster_id',
 'pollster',
 'sponsor_ids',
 'sponsors',
 'display_name',
 'pollster_rating_id',
 'pollster_rating_name',
 'numeric_grade',
 'pollscore',
 'methodology',
 'transparency_score',
 'state',
 'start_date',
 'end_date',
 'sponsor_candidate_id',
 'sponsor_candidate',
 'sponsor_candidate_party',
 'question_id',
 'sample_size',
 'population',
 'subpopulation',
 'population_full',
 'tracking',
 'created_at',
 'notes',
 'url',
 'url_article',
 'url_topline',
 'url_crosstab',
 'source',
 'internal',
 'partisan',
 'politician',
 'politician_id',
 'yes',
 'no',
 'alternate_answers']

In [5]:
table_one = df[['end_date','numeric_grade','pollscore', 'transparency_score', 'sample_size', 'partisan', 'yes', 'no']]

In [6]:
table_one.head()

,end_date,numeric_grade,pollscore,transparency_score,sample_size,partisan,yes,no
0,2/9/26,NaN,NaN,NaN,1000.0,NaN,43.0,57.0
1,2/6/26,NaN,NaN,NaN,21995.0,NaN,39.0,61.0
2,2/9/26,NaN,NaN,NaN,1730.0,NaN,37.0,56.0
3,2/9/26,NaN,NaN,NaN,1551.0,NaN,40.0,57.0
4,2/8/26,NaN,NaN,NaN,NaN,NaN,40.0,54.2

In [7]:
print(table_one['pollscore'].isnull().sum() == len(table_one))
print(table_one['numeric_grade'].isnull().sum() == len(table_one))
print(table_one['transparency_score'].isnull().sum() == len(table_one))
print(table_one['partisan'].isnull().sum() == len(table_one))

True
True
True
False

In [8]:
table_one['partisan'].isnull().sum()

np.int64(726)

In [9]:
df_two = df[['end_date','sample_size','yes', 'no']].dropna()
print(len(df_two))
df_two

734

    end_date  sample_size   yes    no
0     2/9/26       1000.0  43.0  57.0
1     2/6/26      21995.0  39.0  61.0
2     2/9/26       1730.0  37.0  56.0
3     2/9/26       1551.0  40.0  57.0
5     2/5/26       1000.0  44.0  54.0
..       ...          ...   ...   ...
760  1/22/25       2979.0  55.5  37.4
761  1/23/25       1882.0  50.1  49.7
762  1/21/25        742.0  49.0  36.0
763  1/21/25       1077.0  47.0  41.0
764  1/20/25        800.0  56.0  39.0

[734 rows x 4 columns]

In [10]:
df_two['end_date'] = pd.to_datetime(table_one['end_date'])
df_two

C:\Users\Midnight\AppData\Local\Temp\ipykernel_10952\4215076847.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_two['end_date'] = pd.to_datetime(table_one['end_date'])

      end_date  sample_size   yes    no
0   2026-02-09       1000.0  43.0  57.0
1   2026-02-06      21995.0  39.0  61.0
2   2026-02-09       1730.0  37.0  56.0
3   2026-02-09       1551.0  40.0  57.0
5   2026-02-05       1000.0  44.0  54.0
..         ...          ...   ...   ...
760 2025-01-22       2979.0  55.5  37.4
761 2025-01-23       1882.0  50.1  49.7
762 2025-01-21        742.0  49.0  36.0
763 2025-01-21       1077.0  47.0  41.0
764 2025-01-20        800.0  56.0  39.0

[734 rows x 4 columns]

In [12]:
df_two.nunique()

end_date       292
sample_size    385
yes            117
no             133
dtype: int64

In [15]:
def weighted_avg(group, col):
    return (group[col] * group['sample_size']).sum() / group['sample_size'].sum()

result = (
    df.groupby('end_date')
    .apply(lambda g: pd.Series({
        'yes': round(weighted_avg(g, 'yes'), 1),
        'no': round(weighted_avg(g, 'no'), 1)
    }), include_groups=False)
    .reset_index()
)

C:\Users\Midnight\AppData\Local\Temp\ipykernel_10952\3874720113.py:2: RuntimeWarning: invalid value encountered in scalar divide
  return (group[col] * group['sample_size']).sum() / group['sample_size'].sum()

In [16]:
result

    end_date   yes    no
0     1/1/26  38.9  57.5
1    1/11/26  39.7  54.1
2    1/12/26  41.7  55.4
3    1/13/26  40.9  56.1
4    1/14/26  47.3  51.2
..       ...   ...   ...
291   9/3/25  50.0  48.0
292  9/30/25  48.8  48.1
293   9/5/25  44.0  56.0
294   9/8/25  42.8  54.4
295   9/9/25  43.0  55.0

[296 rows x 3 columns]

In [17]:
result[result['yes'] + result['no'] > 100]

Empty DataFrame
Columns: [end_date, yes, no]
Index: []