In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Data/president.csv')
df.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,...,url_topline,url_crosstab,source,internal,partisan,politician,politician_id,yes,no,alternate_answers
0,9f8ab1cd-1a23-421a-8795-1260f1a8d308,15524f36-81eb-4b8c-b19f-663cee931c01,Focaldata,NaN,NaN,Focaldata,837.0,Focaldata,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,37.21,50.66,12.13
1,9f8ab1cd-1a23-421a-8795-1260f1a8d308,15524f36-81eb-4b8c-b19f-663cee931c01,Focaldata,NaN,NaN,Focaldata,837.0,Focaldata,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,39.19,51.47,9.35
2,856d1194-b12c-4403-83f2-8143f7759a65,ae31ea8f-0d54-476d-ab98-61b258a0a986,RMG Research,62ca8b2a-418d-46f9-8c64-1f4a14ba3a80,Napolitan News Service,RMG Research,555.0,RMG Research,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,45.00,53.00,2.00
3,16581cf4-7221-4ed3-8c73-c4bf7f161fe4,4bc528cc-f55c-4f8b-8c90-adfe09f46c76,Morning Consult,NaN,NaN,Morning Consult,218.0,Morning Consult,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,43.95,52.99,3.07
4,0ea785e5-6625-4187-a7e5-44eb3c9fc7b0,3b65bd53-0347-48ff-a808-b054ac635dcc,Angus Reid Global,NaN,NaN,Angus Reid Global,13.0,Angus Reid Global,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Donald Trump,NaN,36.00,56.00,7.00

In [4]:
list(df)

['poll_id',
 'pollster_id',
 'pollster',
 'sponsor_ids',
 'sponsors',
 'display_name',
 'pollster_rating_id',
 'pollster_rating_name',
 'numeric_grade',
 'pollscore',
 'methodology',
 'transparency_score',
 'state',
 'start_date',
 'end_date',
 'sponsor_candidate_id',
 'sponsor_candidate',
 'sponsor_candidate_party',
 'question_id',
 'sample_size',
 'population',
 'subpopulation',
 'population_full',
 'tracking',
 'created_at',
 'notes',
 'url',
 'url_article',
 'url_topline',
 'url_crosstab',
 'source',
 'internal',
 'partisan',
 'politician',
 'politician_id',
 'yes',
 'no',
 'alternate_answers']

In [5]:
df[['start_date', 'end_date']]

    start_date end_date
0       3/6/26  3/10/26
1       3/6/26  3/10/26
2       3/4/26  3/12/26
3       3/6/26   3/8/26
4       3/2/26   3/5/26
..         ...      ...
843    1/19/25  1/22/25
844    1/21/25  1/23/25
845    1/21/25  1/21/25
846    1/20/25  1/21/25
847    1/20/25  1/20/25

[848 rows x 2 columns]

In [12]:
df= df[['end_date','sample_size','yes', 'no']].dropna()
df['end_date'] = pd.to_datetime(df['end_date'])
print(len(df))
df

814

C:\Users\Midnight\AppData\Local\Temp\ipykernel_23068\3953093287.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['end_date'] = pd.to_datetime(df['end_date'])

      end_date  sample_size    yes     no
0   2026-03-10       1782.0  37.21  50.66
1   2026-03-10       1534.0  39.19  51.47
2   2026-03-12       3000.0  45.00  53.00
3   2026-03-08       2202.0  43.95  52.99
4   2026-03-05       1529.0  36.00  56.00
..         ...          ...    ...    ...
843 2025-01-22       2979.0  55.50  37.40
844 2025-01-23       1882.0  50.10  49.70
845 2025-01-21        742.0  49.00  36.00
846 2025-01-21       1077.0  47.00  41.00
847 2025-01-20        800.0  56.00  39.00

[814 rows x 4 columns]

In [13]:
def weighted_avg(group, col):
    return (group[col] * group['sample_size']).sum() / group['sample_size'].sum()

In [14]:
result = (
    df.groupby('end_date')
    .apply(lambda g: pd.Series({
        'yes': round(weighted_avg(g, 'yes'), 1),
        'no': round(weighted_avg(g, 'no'), 1)
    }), include_groups=False)
    .reset_index()
)

In [21]:
result

      end_date   yes    no
0   2025-01-20  56.0  39.0
1   2025-01-21  47.8  39.0
2   2025-01-22  55.5  37.4
3   2025-01-23  54.3  42.6
4   2025-01-24  50.5  44.5
..         ...   ...   ...
311 2026-03-05  36.0  56.0
312 2026-03-08  41.8  54.2
313 2026-03-09  41.4  54.5
314 2026-03-10  38.1  51.0
315 2026-03-12  45.0  53.0

[316 rows x 3 columns]

In [23]:
result.to_csv("Data/approvals_test_data.csv",  encoding='utf-8', index=False)

In [24]:
test = pd.read_csv('Data/approvals_test_data.csv')
test

       end_date   yes    no
0    2025-01-20  56.0  39.0
1    2025-01-21  47.8  39.0
2    2025-01-22  55.5  37.4
3    2025-01-23  54.3  42.6
4    2025-01-24  50.5  44.5
..          ...   ...   ...
311  2026-03-05  36.0  56.0
312  2026-03-08  41.8  54.2
313  2026-03-09  41.4  54.5
314  2026-03-10  38.1  51.0
315  2026-03-12  45.0  53.0

[316 rows x 3 columns]